/*******************************************************************************
 * Copyright 2011 Clockwork
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 09:26:37 PM CET 
//


package nl.clockwork.mule.ebms.stub.ef.model.afleveren.bevestiging;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="tijdstempelOverheidsdeelnemer" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="fout" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}foutType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tijdstempelOverheidsdeelnemer",
    "fout"
})
@XmlRootElement(name = "bevestigAfleverBericht")
public class BevestigAfleverBericht {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tijdstempelOverheidsdeelnemer;
    protected FoutType fout;

    /**
     * Gets the value of the tijdstempelOverheidsdeelnemer property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTijdstempelOverheidsdeelnemer() {
        return tijdstempelOverheidsdeelnemer;
    }

    /**
     * Sets the value of the tijdstempelOverheidsdeelnemer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTijdstempelOverheidsdeelnemer(XMLGregorianCalendar value) {
        this.tijdstempelOverheidsdeelnemer = value;
    }

    /**
     * Gets the value of the fout property.
     * 
     * @return
     *     possible object is
     *     {@link FoutType }
     *     
     */
    public FoutType getFout() {
        return fout;
    }

    /**
     * Sets the value of the fout property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoutType }
     *     
     */
    public void setFout(FoutType value) {
        this.fout = value;
    }

}
