CREATE TABLE cpa
(
	id							INT							GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	cpa_id					VARCHAR(128)		NOT NULL UNIQUE,
	cpa							CLOB						NOT NULL
);

CREATE TABLE ebms_message
(
	id								INT							GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	time_stamp				TIMESTAMP				NOT NULL,
	cpa_id						VARCHAR(256)		NOT NULL,
	conversation_id		VARCHAR(256)		NOT NULL,
	sequence_nr				INT							NOT NULL,
	message_id				VARCHAR(256)		NOT NULL UNIQUE,
	message_type			INT							NOT NULL,
	message_original	BLOB						NULL,
	message_header		CLOB 						NOT NULL,
	message_ack_req		CLOB 						NULL,
	message_manifest	CLOB 						NULL,
	ack_type					INT							NULL,
	ack_header				CLOB 						NULL,
	ack_content				CLOB 						NULL,
	status						INT							NOT NULL,
	status_date				TIMESTAMP				NOT NULL,
	nr_retries				INT							DEFAULT 0 NOT NULL,
	processing_status	INT							NULL,
	next_retry_time		TIMESTAMP				NULL
);

CREATE TABLE ebms_attachment
(
	id								INT							GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	ebms_message_id		INT							NOT NULL FOREIGN KEY REFERENCES ebms_message(id),
	name							VARCHAR(128)		NOT NULL,
	content_type			VARCHAR(64)			NOT NULL,
	content						BLOB						NOT NULL
);
