CREATE TABLE cpa
(
	id							INT							GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	cpa_id					VARCHAR(128)		NOT NULL UNIQUE,
	cpa							CLOB						NOT NULL
);

CREATE TABLE ebms_channel
(
	id								INT						GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	channel_id				VARCHAR(128)	NOT NULL UNIQUE,
	cpa_id						VARCHAR(256)	NOT NULL,
	action_id					VARCHAR(64)		NOT NULL,
	endpoint					VARCHAR(64)		NULL
--	ref_id						INT						NULL FOREIGN KEY REFERENCES ebms_channel(id),
);

CREATE TABLE ebms_message
(
	id										INT							GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
--	parent_id							INT							NULL FOREIGN KEY REFERENCES ebms_message(id),
	time_stamp						TIMESTAMP				NOT NULL,
	cpa_id								VARCHAR(256)		NOT NULL,
	conversation_id				VARCHAR(256)		NOT NULL,
	sequence_nr						INT							NOT NULL,
	message_id						VARCHAR(256)		NOT NULL UNIQUE,
	ref_to_message_id			VARCHAR(256)		NULL,
--	message_type					INT							NOT NULL,
--	message_direction			INT							NOT NULL,
	message_original			BLOB						NULL,
	message_signature			CLOB						NULL,
	message_header				CLOB						NOT NULL,
	message_sync_reply		CLOB						NULL,
	message_order					CLOB						NULL,
	message_ack_req				CLOB						NULL,
	message_ack						CLOB						NULL,
	message_error					CLOB						NULL,
	message_manifest			CLOB						NULL,
--	message_soap_error		CLOB						NULL,
	status								INT							NOT NULL,
	status_date						TIMESTAMP				NOT NULL,
	nr_retries						INT							DEFAULT 0 NOT NULL,
	next_retry_time				TIMESTAMP				NULL
);

CREATE TABLE ebms_attachment
(
	id								INT							GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	ebms_message_id		INT							NOT NULL FOREIGN KEY REFERENCES ebms_message(id),
	name							VARCHAR(128)		NOT NULL,
	content_type			VARCHAR(64)			NOT NULL,
	content						BLOB						NOT NULL
);
