/**
 * Copyright 2011 Clockwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.11 at 02:17:44 PM CEST 
//


package nl.clockwork.mule.ebms.stub.ebf.model.aanleveren.bericht;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kenmerk" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}kenmerkType" minOccurs="0"/>
 *         &lt;element name="berichtsoort" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}berichtsoortType"/>
 *         &lt;element name="aanleverkenmerk" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}aanleverkenmerkType" minOccurs="0"/>
 *         &lt;element name="eerderAanleverkenmerk" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}aanleverkenmerkType" minOccurs="0"/>
 *         &lt;element name="identiteitBelanghebbende" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}identiteitType"/>
 *         &lt;element name="rolBelanghebbende" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}rolType"/>
 *         &lt;element name="identiteitOntvanger" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}identiteitType" minOccurs="0"/>
 *         &lt;element name="rolOntvanger" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}rolType" minOccurs="0"/>
 *         &lt;element name="berichtInhoud" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}berichtInhoudType"/>
 *         &lt;element name="berichtBijlagen" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}berichtBijlagenType" minOccurs="0"/>
 *         &lt;element name="autorisatieAdres" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}autorisatieAdresType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kenmerk",
    "berichtsoort",
    "aanleverkenmerk",
    "eerderAanleverkenmerk",
    "identiteitBelanghebbende",
    "rolBelanghebbende",
    "identiteitOntvanger",
    "rolOntvanger",
    "berichtInhoud",
    "berichtBijlagen",
    "autorisatieAdres"
})
@XmlRootElement(name = "aanleverBericht")
public class AanleverBericht {

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String kenmerk;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String berichtsoort;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String aanleverkenmerk;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String eerderAanleverkenmerk;
    @XmlElement(required = true)
    protected IdentiteitType identiteitBelanghebbende;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rolBelanghebbende;
    protected IdentiteitType identiteitOntvanger;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rolOntvanger;
    @XmlElement(required = true)
    protected BerichtInhoudType berichtInhoud;
    protected BerichtBijlagenType berichtBijlagen;
    protected String autorisatieAdres;

    /**
     * Gets the value of the kenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKenmerk() {
        return kenmerk;
    }

    /**
     * Sets the value of the kenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKenmerk(String value) {
        this.kenmerk = value;
    }

    /**
     * Gets the value of the berichtsoort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBerichtsoort() {
        return berichtsoort;
    }

    /**
     * Sets the value of the berichtsoort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBerichtsoort(String value) {
        this.berichtsoort = value;
    }

    /**
     * Gets the value of the aanleverkenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAanleverkenmerk() {
        return aanleverkenmerk;
    }

    /**
     * Sets the value of the aanleverkenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAanleverkenmerk(String value) {
        this.aanleverkenmerk = value;
    }

    /**
     * Gets the value of the eerderAanleverkenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEerderAanleverkenmerk() {
        return eerderAanleverkenmerk;
    }

    /**
     * Sets the value of the eerderAanleverkenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEerderAanleverkenmerk(String value) {
        this.eerderAanleverkenmerk = value;
    }

    /**
     * Gets the value of the identiteitBelanghebbende property.
     * 
     * @return
     *     possible object is
     *     {@link IdentiteitType }
     *     
     */
    public IdentiteitType getIdentiteitBelanghebbende() {
        return identiteitBelanghebbende;
    }

    /**
     * Sets the value of the identiteitBelanghebbende property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentiteitType }
     *     
     */
    public void setIdentiteitBelanghebbende(IdentiteitType value) {
        this.identiteitBelanghebbende = value;
    }

    /**
     * Gets the value of the rolBelanghebbende property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolBelanghebbende() {
        return rolBelanghebbende;
    }

    /**
     * Sets the value of the rolBelanghebbende property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolBelanghebbende(String value) {
        this.rolBelanghebbende = value;
    }

    /**
     * Gets the value of the identiteitOntvanger property.
     * 
     * @return
     *     possible object is
     *     {@link IdentiteitType }
     *     
     */
    public IdentiteitType getIdentiteitOntvanger() {
        return identiteitOntvanger;
    }

    /**
     * Sets the value of the identiteitOntvanger property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentiteitType }
     *     
     */
    public void setIdentiteitOntvanger(IdentiteitType value) {
        this.identiteitOntvanger = value;
    }

    /**
     * Gets the value of the rolOntvanger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolOntvanger() {
        return rolOntvanger;
    }

    /**
     * Sets the value of the rolOntvanger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolOntvanger(String value) {
        this.rolOntvanger = value;
    }

    /**
     * Gets the value of the berichtInhoud property.
     * 
     * @return
     *     possible object is
     *     {@link BerichtInhoudType }
     *     
     */
    public BerichtInhoudType getBerichtInhoud() {
        return berichtInhoud;
    }

    /**
     * Sets the value of the berichtInhoud property.
     * 
     * @param value
     *     allowed object is
     *     {@link BerichtInhoudType }
     *     
     */
    public void setBerichtInhoud(BerichtInhoudType value) {
        this.berichtInhoud = value;
    }

    /**
     * Gets the value of the berichtBijlagen property.
     * 
     * @return
     *     possible object is
     *     {@link BerichtBijlagenType }
     *     
     */
    public BerichtBijlagenType getBerichtBijlagen() {
        return berichtBijlagen;
    }

    /**
     * Sets the value of the berichtBijlagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BerichtBijlagenType }
     *     
     */
    public void setBerichtBijlagen(BerichtBijlagenType value) {
        this.berichtBijlagen = value;
    }

    /**
     * Gets the value of the autorisatieAdres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutorisatieAdres() {
        return autorisatieAdres;
    }

    /**
     * Sets the value of the autorisatieAdres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutorisatieAdres(String value) {
        this.autorisatieAdres = value;
    }

}
