/*******************************************************************************
 * Copyright 2011 Clockwork
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.11 at 02:17:44 PM CEST 
//


package nl.clockwork.mule.ebms.stub.ebf.model.aanleveren.bericht;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						Beschrijving			:	Een of meer bijlagen bij het bedrijfsdocument. Of daadwerkelijk bijlagen kunnen worden toegevoegd hangt af van 
 * 														het verwerkingsproces.
 * 					
 * 
 * <p>Java class for berichtBijlagenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="berichtBijlagenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bijlage" type="{http://logius.nl/digipoort/ebms/2.0/aanleverservice/1.1/}berichtInhoudType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "berichtBijlagenType", propOrder = {
    "bijlage"
})
public class BerichtBijlagenType {

    @XmlElement(required = true)
    protected List<BerichtInhoudType> bijlage;

    /**
     * Gets the value of the bijlage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bijlage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBijlage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BerichtInhoudType }
     * 
     * 
     */
    public List<BerichtInhoudType> getBijlage() {
        if (bijlage == null) {
            bijlage = new ArrayList<BerichtInhoudType>();
        }
        return this.bijlage;
    }

}
