CREATE TABLE ebms_message
(
	id										INT							IDENTITY(1,1)	PRIMARY KEY,
--	parent_id							INT							NULL FOREIGN KEY REFERENCES ebms_message(id),
	time_stamp						DATETIME				NOT NULL,
	cpa_id								VARCHAR(256)		NOT NULL,
	conversation_id				VARCHAR(256)		NOT NULL,
	sequence_nr						INT							NOT NULL,
	message_id						VARCHAR(256)		NOT NULL UNIQUE,
	ref_to_message_id			VARCHAR(256)		NULL,
	message_type					INT							NOT NULL,
	message_direction			INT							NOT NULL,
	message_original			IMAGE						NULL,
	message_header				TEXT						NOT NULL,
--	message_order					TEXT						NULL,
	message_ack_req				TEXT						NULL,
	message_sync_reply		TEXT						NULL,
	message_ack						TEXT						NULL,
	message_error					TEXT						NULL,
	message_manifest			TEXT						NULL,
--	message_status_req		TEXT						NULL,
--	message_status_res		TEXT						NULL,
	message_soap_error		TEXT						NULL,
	status								INT							NOT NULL,
	status_date						DATETIME				NOT NULL,
	nr_retries						INT							DEFAULT 0 NOT NULL,
	next_retry_time				DATETIME				NULL
);

CREATE TABLE ebms_message
(
	id										INT							IDENTITY(1,1)	PRIMARY KEY,
--	parent_id							INT							NULL FOREIGN KEY REFERENCES ebms_message(id),
	time_stamp						DATETIME				NOT NULL,
	cpa_id								VARCHAR(256)		NOT NULL,
	conversation_id				VARCHAR(256)		NOT NULL,
	sequence_nr						INT							NOT NULL,
	message_id						VARCHAR(256)		NOT NULL UNIQUE,
	message_type					INT							NOT NULL,
	message_direction			INT							NOT NULL,
	message_original			IMAGE						NULL,
	message_header				TEXT						NOT NULL,
--	message_order					TEXT						NULL,
	message_ack_req				TEXT						NULL,
	message_sync_reply		TEXT						NULL,
	message_manifest			TEXT						NULL,
--	message_status_req		TEXT						NULL,
--	message_status_res		TEXT						NULL,
	ack_type							INT							NULL,
	ack_header						TEXT						NULL,
	ack_ack								TEXT						NULL,
	ack_error							TEXT						NULL,
	ack_soap_error				TEXT						NULL,
	status								INT							NOT NULL,
	status_date						DATETIME				NOT NULL,
	nr_retries						INT							DEFAULT 0 NOT NULL,
	next_retry_time				DATETIME				NULL
);

