#
# Copyright 2011 Clockwork
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#-------------------------------------------------------------------------------
# Default config properties
#-------------------------------------------------------------------------------

maxItemsPerPage=20

service.ebms.url=http://localhost:8080/adapter

ebms.host=0.0.0.0
ebms.port=8888
ebms.path=/ebms
ebms.ssl=true
ebms.verifyHostnames=true
ebms.echoHeaderNames=
ebms.connectionLimit=
ebms.queriesPerSecond=
ebms.userQueriesPerSecond=
ebms.cors.allowOrigins=

https.protocols=TLSv1.2
https.cipherSuites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
https.requireClientAuthentication=false
https.clientCertificateHeader=

logging.mdc.audit=DISABLED
logging.mdc.headerNames=

keystore.type=PKCS12
keystore.path=nl/clockwork/ebms/keystore.p12
keystore.password=password
keystore.defaultAlias=

# API Web Server Configuration
api.host=0.0.0.0
api.port=8080
api.path=/
api.ssl.enabled=false
api.ssl.keyStoreType=PKCS12
api.ssl.keyStorePath=nl/clockwork/ebms/keystore.p12
api.ssl.keyStorePassword=password
api.ssl.protocols=
api.ssl.cipherSuites=
api.ssl.clientAuthentication=false
api.ssl.trustStoreType=PKCS12
api.ssl.trustStorePath=
api.ssl.trustStorePassword=
api.ssl.clientTrustStoreType=PKCS12
api.ssl.clientTrustStorePath=
api.ssl.clientTrustStorePassword=

# API Health Service
api.health.enabled=false
api.health.port=8008

# API Server Filters
api.server.connectionLimit=
api.server.queriesPerSecond=
api.server.userQueriesPerSecond=

# API Logging
api.logging.audit.enabled=false
api.logging.echoHeaderNames=
api.logging.mdcHeaderNames=

# API JMX
api.jmx.enabled=false
api.jmx.port=1999
api.jmx.accessFile=
api.jmx.passwordFile=

# API Config
api.configDir=

# Datastore
ebms.jdbc.driverClassName=org.h2.Driver
ebms.jdbc.url=jdbc:h2:tcp://localhost:9092/./h2
ebms.jdbc.username=sa
ebms.jdbc.password=
