/*******************************************************************************
 * Copyright 2011 Clockwork
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 09:26:36 PM CET 
//


package nl.clockwork.mule.ebms.stub.ef.model.afleveren.bericht;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="berichtkenmerk" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}berichtkenmerkType"/>
 *         &lt;element name="kenmerk" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}kenmerkType"/>
 *         &lt;element name="aanleverkenmerk" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}aanleverkenmerkType"/>
 *         &lt;element name="berichtsoort" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}berichtsoortType"/>
 *         &lt;element name="bedrijfsnummer" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}identificatieNummer"/>
 *         &lt;element name="tijdstempelOntvangst" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="berichtinhoud" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}berichtinhoudType"/>
 *         &lt;element name="berichtbijlagen" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}bijlagenType" minOccurs="0"/>
 *         &lt;element name="foutLijst" type="{http://logius.nl/digipoort/ebms/2.0/afleverservice/1.0/}foutLijstType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "berichtkenmerk",
    "kenmerk",
    "aanleverkenmerk",
    "berichtsoort",
    "bedrijfsnummer",
    "tijdstempelOntvangst",
    "berichtinhoud",
    "berichtbijlagen",
    "foutLijst"
})
@XmlRootElement(name = "afleverBericht")
public class AfleverBericht {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String berichtkenmerk;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String kenmerk;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String aanleverkenmerk;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String berichtsoort;
    @XmlElement(required = true)
    protected IdentificatieNummer bedrijfsnummer;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tijdstempelOntvangst;
    @XmlElement(required = true)
    protected BerichtinhoudType berichtinhoud;
    protected BijlagenType berichtbijlagen;
    protected FoutLijstType foutLijst;

    /**
     * Gets the value of the berichtkenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBerichtkenmerk() {
        return berichtkenmerk;
    }

    /**
     * Sets the value of the berichtkenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBerichtkenmerk(String value) {
        this.berichtkenmerk = value;
    }

    /**
     * Gets the value of the kenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKenmerk() {
        return kenmerk;
    }

    /**
     * Sets the value of the kenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKenmerk(String value) {
        this.kenmerk = value;
    }

    /**
     * Gets the value of the aanleverkenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAanleverkenmerk() {
        return aanleverkenmerk;
    }

    /**
     * Sets the value of the aanleverkenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAanleverkenmerk(String value) {
        this.aanleverkenmerk = value;
    }

    /**
     * Gets the value of the berichtsoort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBerichtsoort() {
        return berichtsoort;
    }

    /**
     * Sets the value of the berichtsoort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBerichtsoort(String value) {
        this.berichtsoort = value;
    }

    /**
     * Gets the value of the bedrijfsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificatieNummer }
     *     
     */
    public IdentificatieNummer getBedrijfsnummer() {
        return bedrijfsnummer;
    }

    /**
     * Sets the value of the bedrijfsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificatieNummer }
     *     
     */
    public void setBedrijfsnummer(IdentificatieNummer value) {
        this.bedrijfsnummer = value;
    }

    /**
     * Gets the value of the tijdstempelOntvangst property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTijdstempelOntvangst() {
        return tijdstempelOntvangst;
    }

    /**
     * Sets the value of the tijdstempelOntvangst property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTijdstempelOntvangst(XMLGregorianCalendar value) {
        this.tijdstempelOntvangst = value;
    }

    /**
     * Gets the value of the berichtinhoud property.
     * 
     * @return
     *     possible object is
     *     {@link BerichtinhoudType }
     *     
     */
    public BerichtinhoudType getBerichtinhoud() {
        return berichtinhoud;
    }

    /**
     * Sets the value of the berichtinhoud property.
     * 
     * @param value
     *     allowed object is
     *     {@link BerichtinhoudType }
     *     
     */
    public void setBerichtinhoud(BerichtinhoudType value) {
        this.berichtinhoud = value;
    }

    /**
     * Gets the value of the berichtbijlagen property.
     * 
     * @return
     *     possible object is
     *     {@link BijlagenType }
     *     
     */
    public BijlagenType getBerichtbijlagen() {
        return berichtbijlagen;
    }

    /**
     * Sets the value of the berichtbijlagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BijlagenType }
     *     
     */
    public void setBerichtbijlagen(BijlagenType value) {
        this.berichtbijlagen = value;
    }

    /**
     * Gets the value of the foutLijst property.
     * 
     * @return
     *     possible object is
     *     {@link FoutLijstType }
     *     
     */
    public FoutLijstType getFoutLijst() {
        return foutLijst;
    }

    /**
     * Sets the value of the foutLijst property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoutLijstType }
     *     
     */
    public void setFoutLijst(FoutLijstType value) {
        this.foutLijst = value;
    }

}
