/*******************************************************************************
 * Copyright 2011 Clockwork
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 09:26:36 PM CET 
//


package nl.clockwork.mule.ebms.stub.ef.model.afleveren.bericht;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.ez.ezpoort.model.ebms.afleveren package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.ez.ezpoort.model.ebms.afleveren
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FoutType }
     * 
     */
    public FoutType createFoutType() {
        return new FoutType();
    }

    /**
     * Create an instance of {@link FoutLijstType }
     * 
     */
    public FoutLijstType createFoutLijstType() {
        return new FoutLijstType();
    }

    /**
     * Create an instance of {@link BijlagenType }
     * 
     */
    public BijlagenType createBijlagenType() {
        return new BijlagenType();
    }

    /**
     * Create an instance of {@link IdentificatieNummer }
     * 
     */
    public IdentificatieNummer createIdentificatieNummer() {
        return new IdentificatieNummer();
    }

    /**
     * Create an instance of {@link AfleverBericht }
     * 
     */
    public AfleverBericht createAfleverBericht() {
        return new AfleverBericht();
    }

    /**
     * Create an instance of {@link BerichtinhoudType }
     * 
     */
    public BerichtinhoudType createBerichtinhoudType() {
        return new BerichtinhoudType();
    }

}
